-- Seed inicial de productos
insert into public.products (id, name, slug, description, long_description, price, image, category, benefits, ingredients, stock, rating, reviews_count) values
(
  'calm-core',
  'Calm Core',
  'calm-core',
  'Equilibrio emocional y reducción del estrés',
  'Calm Core es una fórmula especializada que combina adaptógenos poderosos como Ashwagandha, Rhodiola Rosea y Magnesio para ayudarte a encontrar tu centro de calma interior. Diseñado para personas que enfrentan los desafíos del estrés diario, este suplemento apoya la regulación natural del cortisol y promueve un estado de bienestar mental sostenible.',
  899.00,
  'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/1-9iVxN6Ny5U3oIubg4zAwQ75cWc63C4.png',
  'stress-anxiety',
  ARRAY['Disminución del estrés y la ansiedad', 'Mejora en la calidad del sueño', 'Soporte del estado de ánimo y bienestar emocional', 'Regulación del cortisol'],
  ARRAY['Ashwagandha (extracto estandarizado)', 'Rhodiola Rosea', 'Magnesio bisglicinato', 'L-teanina'],
  100,
  4.8,
  124
),
(
  'shield-up',
  'Shield Up',
  'shield-up',
  'Fortalecimiento del sistema inmunológico',
  'Shield Up es tu escudo natural contra los desafíos del día a día. Formulado con una potente combinación de Cola de Pavo, Reishi y Chaga, este suplemento refuerza las defensas naturales de tu cuerpo. Rico en antioxidantes y con propiedades adaptogénicas, Shield Up te ayuda a mantener un sistema inmunológico robusto durante todo el año.',
  949.00,
  'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/2-S6QZ7pqLnL2coqEja0w4z2kn0XkXF2.png',
  'immunity',
  ARRAY['Refuerzo del sistema inmunológico', 'Apoyo de la respuesta natural del cuerpo ante infecciones', 'Aporte antioxidante con vitamina C', 'Mejora de la biodisponibilidad de zinc'],
  ARRAY['Cola de Pavo (extracto)', 'Reishi (Ganoderma lucidum)', 'Chaga (Inonotus obliquus)', 'Vitamina C', 'Zinc quelado'],
  85,
  4.7,
  89
),
(
  'vital-fuel',
  'Vital Fuel',
  'vital-fuel',
  'Energía sostenida y rendimiento físico',
  'Vital Fuel es tu combustible natural para un día lleno de energía. Diseñado con Maca, Ginseng y Cordyceps, este suplemento proporciona un impulso energético sin los picos y caídas del café. Ideal para atletas, profesionales ocupados o cualquiera que busque optimizar su rendimiento físico y mental de manera natural.',
  899.00,
  'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/3-NzZRxLQh1QyHE2MGuaqNQ3UDUh6BmJ.png',
  'energy-performance',
  ARRAY['Aumento de energía física y mental', 'Apoyo al rendimiento durante la actividad física', 'Mejora de la vitalidad sin estimulantes artificiales', 'Aporte de vitaminas y minerales esenciales'],
  ARRAY['Maca (extracto)', 'Ginseng Panax', 'Cordyceps sinensis', 'Vitaminas del complejo B', 'Minerales traza'],
  120,
  4.6,
  156
),
(
  'focus-mind',
  'Focus Mind',
  'focus-mind',
  'Claridad mental y concentración',
  'Focus Mind es tu aliado para alcanzar estados de concentración profunda. Con una fórmula única que combina Ginseng, Rhodiola Rosea y Melón de León, este suplemento apoya la función cognitiva, mejora la memoria y reduce la fatiga mental. Perfecto para estudiantes, profesionales creativos y cualquiera que busque optimizar su rendimiento mental.',
  949.00,
  'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/4-Gl94JLsApZA47o52cnh3Z8is5atr5L.png',
  'cognitive',
  ARRAY['Mejora de la concentración y el enfoque', 'Apoyo a la memoria y rendimiento cognitivo', 'Reducción de la fatiga mental', 'Aporte de vitamina B6'],
  ARRAY['Ginseng (extracto)', 'Rhodiola Rosea', 'Melón de León (Hericium erinaceus)', 'Bacopa monnieri', 'Vitamina B6'],
  95,
  4.9,
  203
),
(
  'oxycell',
  'OxyCell',
  'oxycell',
  'Protección celular y longevidad',
  'OxyCell es tu fórmula antienvejecimiento a nivel celular. Diseñado con poderosos antioxidantes como Vitamina C, Reishi y Chaga, este suplemento protege tus células del daño oxidativo y apoya la longevidad celular. Rico en minerales esenciales como magnesio y zinc, OxyCell es tu aliado para mantener la vitalidad y el bienestar a largo plazo.',
  999.00,
  'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/5-k3IAPaZzbPwj7RdT8pGZMOcMirdIoX.png',
  'longevity',
  ARRAY['Protección contra el daño oxidativo', 'Apoyo a la longevidad y vitalidad celular', 'Aporte de antioxidantes naturales', 'Equilibrio mineral con magnesio y zinc'],
  ARRAY['Vitamina C (ácido ascórbico)', 'Reishi (extracto)', 'Chaga (extracto)', 'Magnesio', 'Zinc', 'Selenio'],
  75,
  4.8,
  67
),
(
  'hormonix',
  'Hormonix',
  'hormonix',
  'Balance hormonal natural',
  'Hormonix es tu solución natural para el equilibrio hormonal. Formulado con Ginseng, Ashwagandha y Maca, este suplemento apoya la función endocrina y ayuda a mantener niveles hormonales saludables. Ideal para personas que buscan equilibrio hormonal, aumento de vitalidad y apoyo al sistema reproductivo de forma natural.',
  949.00,
  'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/6-XHnlh0G7i1EIB1rL9PsqQztFiRhlki.png',
  'hormonal',
  ARRAY['Balance hormonal general', 'Aumento de la vitalidad física y emocional', 'Apoyo adaptógeno al sistema endocrino', 'Reducción del estrés y la fatiga hormonal'],
  ARRAY['Ginseng Panax', 'Ashwagandha (extracto)', 'Maca (extracto)', 'Tribulus terrestris', 'Vitamina D3'],
  110,
  4.7,
  98
)
on conflict (id) do nothing;
